const PRODUCTS = {
  nolberto: {
    id: 'nolberto',
    name: 'Nolberto Espresso',
    price: '$25.00',
    image: 'nolberto.png',
    flavours: '<strong>Flavours:</strong> Stone fruit, creamy, muscovado & grapefruit residual',
    sourcing: '<strong>Colombia</strong>ORIGIN: Planadas, Tolima<br>VARIETAL: Typica Mejorado<br>PRODUCER: Nolberto Olaya',
    process: 'Nolberto and his son Yefferson carefully process each lot, beginning with sorting ripe cherries before fermenting them in sealed barrels to maintain low temperatures. After de-pulping, the coffee undergoes extended fermentation, is washed twice, and then slowly dried—first in marquesinas, then indoors over several weeks—ensuring clarity, stability, and exceptional quality.',
    tasting: 'Stone fruit, creamy, muscovado & grapefruit residual',
    aboutHeading: 'About Nolberto',
    aboutBody: 'Nolberto, a third-generation coffee producer with over 24 years of experience, is known for his expertise in organic and regenerative farming. He manages his farm holistically, producing his own natural fertilisers and cultivating a diverse range of varieties including Caturra, Gesha, Pink Bourbon, and Java. With most of the farm under shade trees, his approach supports soil health, biodiversity, and resilience to changing climate conditions resulting in consistently healthy harvests and exceptional quality.',
    aboutPhoto: 'nolberto-photo.png',
    transparency: 'We pay above Fair Trade prices and publish full pricing breakdowns for all our coffees.',
    moreAbout: 'Small Batch Roasting Co. has been roasting in North Melbourne since 2008.',
    recommended: ['candyman', 'golden-filter', 'alirio', 'beto']
  },
  candyman: {
    id: 'candyman',
    name: 'Candyman Espresso Blend',
    price: '$20.00',
    image: 'candyman.png',
    flavours: '<strong>Flavours:</strong> Milk chocolate, caramel, red apple',
    sourcing: '<strong>Colombia & Ethiopia</strong><br>ORIGIN: Various<br>VARIETAL: Mixed<br>PRODUCER: Various',
    process: 'A carefully crafted blend combining Colombian and Ethiopian coffees, roasted to highlight sweetness and balance.',
    tasting: 'Milk chocolate, caramel, red apple',
    aboutHeading: 'About Candyman',
    aboutBody: 'Candyman is our flagship espresso blend, launched in 2010. It\'s our daily labour of love, a constant work-in-progress: making superlative tastiness from the raw components that we insist on buying well, ourselves (ie not just from the importer as is common practice) All this to create sweet, balanced espresso, with or without milk.',
    aboutPhoto: 'candyman_photo.png',
    transparency: 'We pay above Fair Trade prices and publish full pricing breakdowns for all our coffees.',
    moreAbout: 'Small Batch Roasting Co. has been roasting in North Melbourne since 2008.',
    recommended: ['nolberto', 'golden-filter', 'beto', 'white']
  },
  'golden-filter': {
    id: 'golden-filter',
    name: 'Golden Ticket-Filter',
    price: '$20.00',
    image: 'golden filter.png',
    flavours: '<strong>Flavours:</strong> Juicy, bright, stone fruit',
    sourcing: '<strong>Colombia</strong><br>ORIGIN: Huila<br>VARIETAL: Caturra<br>PRODUCER: Various',
    process: 'Washed process, dried on raised beds.',
    tasting: 'Juicy, bright, stone fruit',
    aboutHeading: 'About Golden Ticket',
    aboutBody: 'Our everyday filter coffee. Bright, clean and endlessly drinkable.',
    aboutPhoto: 'nolberto-photo.png',
    transparency: 'We pay above Fair Trade prices and publish full pricing breakdowns for all our coffees.',
    moreAbout: 'Small Batch Roasting Co. has been roasting in North Melbourne since 2008.',
    recommended: ['nolberto', 'alirio', 'jhoan', 'estrellas']
  },
  alirio: {
    id: 'alirio',
    name: 'Alirio Munoz-Filter',
    price: '$24.00',
    image: 'AlirioFilter.png',
    flavours: '<strong>Flavours:</strong> Peach, floral, clean',
    sourcing: '<strong>Colombia</strong><br>ORIGIN: Caturron<br>VARIETAL: Caturra<br>PRODUCER: Alirio Munoz',
    process: 'Washed process with extended fermentation.',
    tasting: 'Peach, floral, clean',
    aboutHeading: 'About Alirio',
    aboutBody: 'Alirio Munoz is a dedicated producer from Caturron, Colombia, known for his meticulous approach to fermentation and drying.',
    aboutPhoto: 'candyman_photo.png',
    transparency: 'We pay above Fair Trade prices and publish full pricing breakdowns for all our coffees.',
    moreAbout: 'Small Batch Roasting Co. has been roasting in North Melbourne since 2008.',
    recommended: ['nolberto', 'golden-filter', 'jhoan', 'estrellas']
  },
  beto: {
    id: 'beto',
    name: 'Beto-Pink Bourbon Espresso',
    price: '$24.00',
    image: 'beto_espresso.png',
    flavours: '<strong>Flavours:</strong> Raspberry, brown sugar, milk chocolate',
    sourcing: '<strong>Colombia</strong><br>ORIGIN: Huila<br>VARIETAL: Pink Bourbon<br>PRODUCER: Beto',
    process: 'Natural process, dried on raised beds.',
    tasting: 'Raspberry, brown sugar, milk chocolate',
    aboutHeading: 'About Beto',
    aboutBody: 'A standout Pink Bourbon grown in the hills of Huila, Colombia.',
    aboutPhoto: 'nolberto-photo.png',
    transparency: 'We pay above Fair Trade prices and publish full pricing breakdowns for all our coffees.',
    moreAbout: 'Small Batch Roasting Co. has been roasting in North Melbourne since 2008.',
    recommended: ['nolberto', 'candyman', 'white', 'golden-filter']
  },
  white: {
    id: 'white',
    name: 'The Ones We Love-Espresso',
    price: '$21.00',
    image: 'white.png',
    flavours: '<strong>Flavours:</strong> Toffee, walnut, dried fruit',
    sourcing: '<strong>Colombia & Brazil</strong><br>ORIGIN: Various<br>VARIETAL: Mixed<br>PRODUCER: Various',
    process: 'Blended and roasted to work beautifully with milk.',
    tasting: 'Toffee, walnut, dried fruit',
    aboutHeading: 'About The Ones We Love',
    aboutBody: 'Our milk-based espresso blend. Rich, sweet and comforting.',
    aboutPhoto: 'candyman_photo.png',
    transparency: 'We pay above Fair Trade prices and publish full pricing breakdowns for all our coffees.',
    moreAbout: 'Small Batch Roasting Co. has been roasting in North Melbourne since 2008.',
    recommended: ['candyman', 'nolberto', 'beto', 'golden-filter']
  },
  jhoan: {
    id: 'jhoan',
    name: 'Jhoan Vergara-Filter',
    price: '$21.00',
    image: 'JhoanFilter.png',
    flavours: '<strong>Flavours:</strong> Pink Bourbon, floral, sweet',
    sourcing: '<strong>Colombia</strong><br>ORIGIN: Pink Bourbon<br>VARIETAL: Pink Bourbon<br>PRODUCER: Jhoan Vergara',
    process: 'Natural process, carefully dried.',
    tasting: 'Pink Bourbon, floral, sweet',
    aboutHeading: 'About Jhoan',
    aboutBody: 'Jhoan Vergara produces exceptional Pink Bourbon coffees in Colombia.',
    aboutPhoto: 'nolberto-photo.png',
    transparency: 'We pay above Fair Trade prices and publish full pricing breakdowns for all our coffees.',
    moreAbout: 'Small Batch Roasting Co. has been roasting in North Melbourne since 2008.',
    recommended: ['alirio', 'golden-filter', 'estrellas', 'nolberto']
  },
  estrellas: {
    id: 'estrellas',
    name: 'Las Estrellas de Ají-Filter',
    price: '$25.00',
    image: 'EstrellasFilter.png',
    flavours: '<strong>Flavours:</strong> Tropical fruit, complex, bright',
    sourcing: '<strong>Colombia</strong><br>ORIGIN: Colombia<br>VARIETAL: Various<br>PRODUCER: Various',
    process: 'Extended fermentation, washed.',
    tasting: 'Tropical fruit, complex, bright',
    aboutHeading: 'About Las Estrellas',
    aboutBody: 'A complex and vibrant filter coffee from Colombia.',
    aboutPhoto: 'candyman_photo.png',
    transparency: 'We pay above Fair Trade prices and publish full pricing breakdowns for all our coffees.',
    moreAbout: 'Small Batch Roasting Co. has been roasting in North Melbourne since 2008.',
    recommended: ['alirio', 'jhoan', 'golden-filter', 'nolberto']
  },
  'espresso-bundle': {
    id: 'espresso-bundle',
    name: 'Espresso-Bundle',
    price: '$21.00',
    image: 'EspressoBundle.jpeg',
    flavours: '<strong>Flavours:</strong> Varied — includes our best espresso roasts',
    sourcing: '<strong>Colombia & Ethiopia</strong><br>ORIGIN: Various<br>VARIETAL: Mixed<br>PRODUCER: Various',
    process: 'A curated selection of our best espresso coffees bundled together.',
    tasting: 'Varied across the bundle',
    aboutHeading: 'About the Espresso Bundle',
    aboutBody: 'The perfect way to explore our espresso range. Includes a selection of our most popular espresso roasts.',
    aboutPhoto: 'nolberto-photo.png',
    transparency: 'We pay above Fair Trade prices and publish full pricing breakdowns for all our coffees.',
    moreAbout: 'Small Batch Roasting Co. has been roasting in North Melbourne since 2008.',
    recommended: ['candyman', 'nolberto', 'beto', 'white']
  },
  'filter-bundle': {
    id: 'filter-bundle',
    name: 'Filter-Bundle',
    price: '$25.00',
    image: 'FilterBundle.jpeg',
    flavours: '<strong>Flavours:</strong> Varied — includes our best filter roasts',
    sourcing: '<strong>Colombia</strong><br>ORIGIN: Various<br>VARIETAL: Mixed<br>PRODUCER: Various',
    process: 'A curated selection of our best filter coffees bundled together.',
    tasting: 'Varied across the bundle',
    aboutHeading: 'About the Filter Bundle',
    aboutBody: 'The perfect way to explore our filter range. Includes a selection of our most popular filter roasts.',
    aboutPhoto: 'candyman_photo.png',
    transparency: 'We pay above Fair Trade prices and publish full pricing breakdowns for all our coffees.',
    moreAbout: 'Small Batch Roasting Co. has been roasting in North Melbourne since 2008.',
    recommended: ['golden-filter', 'alirio', 'jhoan', 'estrellas']
  },
  combo: {
    id: 'combo',
    name: 'Filter x Espresso Combo',
    price: '$28.00',
    image: 'ComboBundle.jpeg',
    flavours: '<strong>Flavours:</strong> Varied — best of both worlds',
    sourcing: '<strong>Colombia & Ethiopia</strong><br>ORIGIN: Various<br>VARIETAL: Mixed<br>PRODUCER: Various',
    process: 'A mix of our best filter and espresso coffees in one bundle.',
    tasting: 'Varied across the bundle',
    aboutHeading: 'About the Combo Bundle',
    aboutBody: 'Can\'t decide between filter and espresso? Get both. Our combo bundle includes top picks from each range.',
    aboutPhoto: 'nolberto-photo.png',
    transparency: 'We pay above Fair Trade prices and publish full pricing breakdowns for all our coffees.',
    moreAbout: 'Small Batch Roasting Co. has been roasting in North Melbourne since 2008.',
    recommended: ['espresso-bundle', 'filter-bundle', 'candyman', 'golden-filter']
  },
  'decaf-espresso': {
    id: 'decaf-espresso',
    name: 'Decaf-Espresso',
    price: '$20.00',
    image: 'decaf_espresso.png',
    flavours: '<strong>Flavours:</strong> Chocolate, caramel, smooth',
    sourcing: '<strong>Colombia</strong><br>ORIGIN: Various<br>VARIETAL: Mixed<br>PRODUCER: Various',
    process: 'Swiss Water Process decaffeination, preserving the natural flavours of the coffee.',
    tasting: 'Chocolate, caramel, smooth',
    aboutHeading: 'About Decaf Espresso',
    aboutBody: 'All the flavour, none of the caffeine. Our decaf espresso is processed using the Swiss Water Method to retain its natural character.',
    aboutPhoto: 'candyman_photo.png',
    transparency: 'We pay above Fair Trade prices and publish full pricing breakdowns for all our coffees.',
    moreAbout: 'Small Batch Roasting Co. has been roasting in North Melbourne since 2008.',
    recommended: ['decaf-filter', 'candyman', 'white', 'nolberto']
  },
  'decaf-filter': {
    id: 'decaf-filter',
    name: 'Decaf-Filter',
    price: '$20.00',
    image: 'decaf filter.jpeg',
    flavours: '<strong>Flavours:</strong> Stone fruit, gentle, sweet',
    sourcing: '<strong>Colombia</strong><br>ORIGIN: Various<br>VARIETAL: Mixed<br>PRODUCER: Various',
    process: 'Swiss Water Process decaffeination, preserving the natural flavours of the coffee.',
    tasting: 'Stone fruit, gentle, sweet',
    aboutHeading: 'About Decaf Filter',
    aboutBody: 'A gentle, flavourful decaf perfect for filter brewing. Processed using the Swiss Water Method.',
    aboutPhoto: 'nolberto-photo.png',
    transparency: 'We pay above Fair Trade prices and publish full pricing breakdowns for all our coffees.',
    moreAbout: 'Small Batch Roasting Co. has been roasting in North Melbourne since 2008.',
    recommended: ['decaf-espresso', 'golden-filter', 'alirio', 'jhoan']
  }
};